### ISSUE TITLE
a requirement

### ISSUE THREAD

**Issue by alexliyang** [abreheret/PixelAnnotationTool#1]
Hi, I test the app , it is very good.

when I use it, I find some questions:
1. select label  sometimes error
2. GrabCut can be imported in
3. merge the watershed label and mask and let the mask fine (manually must  give scratch all mask area )

**Comment by abreheret** [comment]
Hi,

1 - For the first question, can you be more specific in your question. What is the error when you select the label ?
2 - In the next version, I could integrate the GrabCut (I did not know this method), I need to test and see if it's relevant.
3 - Merge the watershed and mask, what do you mean ? in the directory, you will find 2 files for each image annotate : The watershed file and the mask file (dissociated). How would you like merge theses files ?

**Comment by alexliyang** [comment]
Hi:
   For the first question, maybe I use it an uncorrectly, but sometimes I confused these label selections and I can not describe the confuse clearly :( .
   For the third question,  my required is  getting a mask , but the watershed result is only edge annotation. I hope watershed result can get the result like Grabcut result, maye your latter version grabcut will come true.

Thank you verymuch & hope your new version

**Comment by abreheret** [comment]
I do not see the usefulness of GrabCut for this tool. So I close this issue
