### ISSUE TITLE
Save mask does not respond

### ISSUE THREAD

**Issue by mldm4** [abreheret/PixelAnnotationTool#10]
I am loading a directory containing only .jpg images.
Some them are normally saved, but some others just do not respond when clicking 'Save current image' nor pressing 'Ctrl+S'. I have checked it happens always on the same images. I do not see any particular common pattern among them that could give me a hint of what is going on.
I wonder if you have any idea of what could possibly be the reason.

Thanks.

**Comment by abreheret** [comment]
How much image do you have in your directory ?  
Do you have a lot of memory ram ?
The bug reproduce also on Windows OS ?
I would like to reproduce this bug on my PC.

Thanks,

**Comment by akileshbadrinaaraayanan** [comment]
1. Around 120 images in directory.
2. Sufficient memory RAM.
3. Not sure about Windows OS.

Thanks,
Akilesh

**Comment by akileshbadrinaaraayanan** [comment]
@abreheret : Were you able to reproduce this bug?

**Comment by mldm4** [comment]
It is the same for me. I have 60 images, 8G RAM. I don't have any Windows machine available.

**Comment by abreheret** [comment]
I do not have linux on hand at the moment, I will try to reproduce this bug as soon as possible.
What is your linux distribution ?

**Comment by mldm4** [comment]
Ubuntu 16.04

**Comment by sebastianor** [comment]
Same here on MacOS High Sierra 10.13.4

**Comment by TomKomar** [comment]
Same on Win10. 16GB RAM, 100 small images (35x320). Stop saving at random times.

**Comment by PROGrand** [comment]
this is a bug in utils.cpp isFullZero:
replace width with bytesPerLine.

bool isFullZero(const QImage& image) {
...
		for (int x = 0; x < image.bytesPerLine(); x++) {
...
	}
	return true;
}

**Comment by abreheret** [comment]
fix in [v1.3.1](https://github.com/abreheret/PixelAnnotationTool/releases/tag/v1.3.1)
