### ISSUE TITLE
XML annotations for objects

### ISSUE THREAD

**Issue by suj97** [abreheret/PixelAnnotationTool#11]
Hi,

It would be a nice addition if we can also get XML annotations for the bounding box of each mask as this (the bounding boxes) is an essential requirement for training Mask-RCNN models on tensorflow or any other library.

Thanks in advance.

**Comment by abreheret** [comment]
The PixelAnnotationTool is not designed for the bounding box annotation. If you need, go to a other tool like this : https://github.com/tzutalin/labelImg
