### ISSUE TITLE
App crashes on Windows 10, when I try to load file with local chars in filename

### ISSUE THREAD

**Issue by LachubCz** [abreheret/PixelAnnotationTool#15]
When I try to load file "Výstřižek.jpg" app crashes every time. When I try to load file "Vystrizek.jpg" everything works fine.

**Comment by ustcjerry** [comment]
same here, when the path contain local chars, the exe will crashes.

**Comment by bharath5673** [comment]
WINDOWS users can use this page .. its cool

https://github.com/tenjumh/Pixel-Annotation-Tool

**Comment by abreheret** [comment]
Sorry, but the software does not managing accented characters. Give me pulls requests if you want to have this feature.
