### ISSUE TITLE
MacOS build

### ISSUE THREAD

**Issue by andscova** [abreheret/PixelAnnotationTool#16]
Hi,

is there any plan for a MacOS build?
Best,

a.

**Comment by abreheret** [comment]
Sorry, for the moment, I don't support building for MAC OS.

**Comment by abreheret** [comment]
It done ! [v1.3.1](https://github.com/abreheret/PixelAnnotationTool/releases/tag/v1.3.1)

**Comment by andscova** [comment]
Hello,

thank you for the build!

However I got this error while installing:

Dyld Error Message:
  Library not loaded: @rpath/libopencv_xfeatures2d.3.4.dylib
  Referenced from: /private/var/folders/9g/695vzwfj58b1sc4rn48_34zh0000gn/T/AppTranslocation/706398C3-3A31-4917-A73C-36973ADDF37A/d/PixelAnnotationTool.app/Contents/Frameworks/libopencv_stitching.3.4.dylib
  Reason: image not found

**Comment by abreheret** [comment]
try before in commande line `brew install opencv`

**Comment by andscova** [comment]
Cool looks like it's working now! Thanks!

**Comment by vlordier** [comment]
> Cool looks like it's working now! Thanks!
@andscova having the same issue despite opencv up and setup
did you do something else to get it up and running ?
