### ISSUE TITLE
How do I go about hosting this application onto a webpage, provided I downloaded the .AppImage file?

### ISSUE THREAD

**Issue by captain-america96** [abreheret/PixelAnnotationTool#19]
Might not be super relevant but I'm planning on using this along with mechanical Turk, and for that I should be able to host this onto my own webserver. How can I achieve this? Any sort of primer on approaching this problem would be more than helpful thanks!!

**Comment by abreheret** [comment]
Sorry I dont know Amazon Mechanical Turk. If you want, you can host this application onto your webpage. The releases are available here :  https://github.com/abreheret/PixelAnnotationTool/releases
