### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by usernoble** [abreheret/PixelAnnotationTool#2]
HI
I fine one problem is When i use your app to  finish color mask on picture and saved, but open the file (GMIP software), the pixel edge has a little no match (some pixel disappear).
Is the software operation wrong?
please help.
Thanks

**Comment by abreheret** [comment]
Hi,
If you talk about the white pixels (in the `*watershed_mask.png` see below). These pixels are situated on the border between two labels area. Its normal. 
Normally, this border doesn't exist in the v1.1.0 in the `*watershed_color.png` but exists always in the `*watershed_mask.png`
<img src="https://raw.githubusercontent.com/abreheret/PixelAnnotationTool/master/images_test/road1_watershed_mask.png" width="650"/>

**Comment by usernoble** [comment]
Hi
t it will help me alot
hx~~
