### ISSUE TITLE
About Build

### ISSUE THREAD

**Issue by PhilipWu526** [abreheret/PixelAnnotationTool#22]
Hello,
I am using Ubuntu 16.04 .

Below is in your script to build,

On ubuntu, PixelAnnotationTool need this pacakage (OpenCV and Qt5.9.1):
Step 1:
``
sudo apt-get install mesa-common-dev
sudo apt-get install libopencv-dev python-opencv
wget http://download.qt.io/official_releases/qt/5.9/5.9.1/qt-opensource-linux-x64-5.9.1.run
chmod +x qt-opensource-linux-x64-5.9.1.run
./qt-opensource-linux-x64-5.9.1.run
``

To compile the application :
Step 2:
``
cd ..
mkdir x64
cd x64
cmake -DQT5_DIR=/path/to/Qt5.9.1/5.9.1/gcc_64/lib/cmake -G "Unix Makefiles" ..
make
``

But when I do 
``
cmake -DQT5_DIR=/path/to/Qt5.9.1/5.9.1/gcc_64/lib/cmake -G "Unix Makefiles" ..
``
I encounter some error.

Now, I finished Step1 and downloaded PixelAnnotationTool_x86_64_v1.3.1.AppImage and 
PixelAnnotationTool_x64_v1.3.1.zip and do 
``
chmod +x PixelAnnotationTool_x86_64_v1.3.1.AppImage
``
, but i am not sure it was right.

So , I want to know what are the **necessary things** i need to install before using PixelAnnotationTool.

Thanks!

**Comment by ekudritski** [comment]
If you want to combile then you need to change the path.  In my case i changed `/path/to/Qt5.9.1/5.9.1/gcc_64/lib/cmake` to `/opt/Qt/5.11.1/gcc_64/lib/cmake`
It depends where you installed it.

**Comment by PallawiSinghal** [comment]
How to run the tool after compiling it.please help me.

**Comment by PallawiSinghal** [comment]
> Hello,
> I am using Ubuntu 16.04 .
> 
> Below is in your script to build,
> 
> On ubuntu, PixelAnnotationTool need this pacakage (OpenCV and Qt5.9.1):
> Step 1:
> `sudo apt-get install mesa-common-dev sudo apt-get install libopencv-dev python-opencv wget http://download.qt.io/official_releases/qt/5.9/5.9.1/qt-opensource-linux-x64-5.9.1.run chmod +x qt-opensource-linux-x64-5.9.1.run ./qt-opensource-linux-x64-5.9.1.run`
> 
> To compile the application :
> Step 2:
> `cd .. mkdir x64 cd x64 cmake -DQT5_DIR=/path/to/Qt5.9.1/5.9.1/gcc_64/lib/cmake -G "Unix Makefiles" .. make`
> 
> But when I do
> `cmake -DQT5_DIR=/path/to/Qt5.9.1/5.9.1/gcc_64/lib/cmake -G "Unix Makefiles" ..`
> I encounter some error.
> 
> Now, I finished Step1 and downloaded PixelAnnotationTool_x86_64_v1.3.1.AppImage and
> PixelAnnotationTool_x64_v1.3.1.zip and do
> `chmod +x PixelAnnotationTool_x86_64_v1.3.1.AppImage`
> , but i am not sure it was right.
> 
> So , I want to know what are the **necessary things** i need to install before using PixelAnnotationTool.
> 
> Thanks!

You can also use the tool labelme for easy and fast use.
