### ISSUE TITLE
Problems with macOS Mojave

### ISSUE THREAD

**Issue by hablema** [abreheret/PixelAnnotationTool#23]
The release doesn't support OSX Mojave (10.14).

**Comment by HairuiLiu** [comment]
same question as miladm. could you add support to Mojave?

**Comment by weltonrodrigo** [comment]
```
Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/Cellar/ffmpeg/4.1.1/lib/libswresample.3.dylib
  Referenced from: /private/var/folders/h8/vxd5l9_17q91pkt5_p57906h0000gp/T/AppTranslocation/FF63E748-10CB-4B84-B73E-E3048F827351/d/PixelAnnotationTool.app/Contents/Frameworks/libavcodec.58.dylib
  Reason: image not found

```

Getting this error on macOS Mojave. This is because the app expects ffmpeg 4.1.1. If I find a solution, will post here.

**Comment by mrvictorn** [comment]
Similar issue here (Mac OSX Mojave 10.14.2), opencv is installed with brew:
```
python3
>>> import cv2
>>> print(cv2.__version__)
4.1.0
```
Install fails with 
Dyld Error Message:
  Library not loaded: @rpath/libopencv_imgproc.4.0.dylib

How could I address this?

**Comment by gitchrisqueen** [comment]
Same issue when trying to use on MAC OSX Mojave 10.14.4. Opencv installed with brew 

> Dyld Error Message:
Library not loaded: @rpath/libopencv_imgproc.4.0.dylib
Referenced from: /Applications/PixelAnnotationTool.app/Contents/Frameworks/libopencv_gapi.4.0.dylib
Reason: image not found

**Comment by benjaminvdb** [comment]
> Same issue when trying to use on MAC OSX Mojave 10.14.4. Opencv installed with brew
> 
> > Dyld Error Message:
> > Library not loaded: @rpath/libopencv_imgproc.4.0.dylib
> > Referenced from: /Applications/PixelAnnotationTool.app/Contents/Frameworks/libopencv_gapi.4.0.dylib
> > Reason: image not found

The current release (v1.3.2) is linked against OpenCV 4.0, while the newest OpenCV on Homebrew is 4.1, resulting in PixelAnnotationTool not being able to find the dynamic library file.

It was easy to build PixelAnnotationTool from sources using the [provided instructions](https://github.com/abreheret/PixelAnnotationTool/blob/master/scripts_to_build/README.md). In my case it was as simple as:

```
git clone https://github.com/abreheret/PixelAnnotationTool.git
cd PixelAnnotationTool
mkdir x64
cd x64
cmake -DQT5_DIR=/usr/local/Cellar/qt/5.12.3/lib/cmake -G "macOS Makefiles" ..
```

Of course you'll need to install qt first, e.g., with Homebrew using `brew install qt`.

**Comment by roryw10** [comment]
this process doesnt work for me @benjaminvdb - i hit error 

CMake Error: Could not create named generator macOS Makefiles

Generators
  Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  Xcode                        = Generate Xcode project files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.

I tried using make with "Unix Makefiles" and at a commmand line things looked good, however when i try and run the pixelannotator it still crashes?

**Comment by benjaminvdb** [comment]
@roryw10 : sorry about the wrong generator in the CMake command. I assumed there was a macOS generator, but I actually used the Unix one. The command you tried is the right one and I've edited my comment above accordingly.

Indeed, it seems that the binary is linked to the correct library, but it doesn't find it when you run it. Since you have `libopencv_gapi.4.1.dylib` under `/usr/local`, have you tried adding Homebrew's library path to your LD_LIBRARY_PATH environment variable, i.e., `export LD_LIBRARY_PATH=/usr/local/lib`? If that works, you can add it to your shell profile (e.g. .bashrc). I already had this set myself, so that's why I could be working for me, but not for you.

**Comment by abreheret** [comment]
For information, I can not help you, because I do not have mac. The macOS [distributed versions](https://github.com/abreheret/PixelAnnotationTool/releases) (dmg file) are made with [travis](https://github.com/abreheret/PixelAnnotationTool/blob/master/.travis.yml).
If you find a stable solution I am interested.

**Comment by RF-Nelson** [comment]
To add to @benjaminvdb's solution for those that may not be familiar with how to compile mac apps:

```
install [Xcode](https://apps.apple.com/us/app/xcode/id497799835?mt=12)
brew install opencv && brew install cmake && brew install qt
git clone https://github.com/abreheret/PixelAnnotationTool.git
cd PixelAnnotationTool
mkdir x64
cd x64
cmake -DQT5_DIR=/usr/local/Cellar/qt/5.12.3/lib/cmake -G "Unix Makefiles" ..
make all
open PixelAnnotationTool.app/
```

**Comment by IsaacPassmore** [comment]
> To add to @benjaminvdb's solution for those that may not be familiar with how to compile mac apps or `Makefile`s:
> 
> First, install [Xcode](https://apps.apple.com/us/app/xcode/id497799835?mt=12).
> 
> Then run the following commands:
> 
> ```
> brew install opencv && brew install cmake && brew install qt
> git clone https://github.com/abreheret/PixelAnnotationTool.git
> cd PixelAnnotationTool
> mkdir x64
> cd x64
> cmake -DQT5_DIR=/usr/local/Cellar/qt/5.12.3/lib/cmake -G "Unix Makefiles" ..
> make all
> open PixelAnnotationTool.app/
> ```

When trying this myself, I had issue at the `make all` step. I was having a failure saying the make file couldn't find the Qt5Widgets. So I needed to edit line 50 of the CMakeLists.txt file located in the PixelAnnotationTool directory. 

Original line:
`find_path(Qt5Widgets_DIR Qt5WidgetsConfig.cmake PATHS "${QT5_DIR}/Qt5Widgets" )`

Correction:
`find_path(Qt5Widgets_DIR Qt5WidgetsConfig.cmake PATHS "/usr/local/Cellar/qt/5.13.1/lib/cmake/Qt5Widgets" )`

Once that was changed running `make` worked just fine.

**Comment by abreheret** [comment]
Do you have alway this problem with the new version 1.4 ?

**Comment by benjaminvdb** [comment]
> Do you have alway this problem with the new version 1.4 ?

@abreheret I can now simply run the v1.4.0 macOS release without building it myself. Thanks! 👍 
<img width="1226" alt="Screenshot 2020-03-05 at 9 22 27" src="https://user-images.githubusercontent.com/8875786/75961831-fed10900-5ec2-11ea-80b2-a8ea8700ffbe.png">
