### ISSUE TITLE
XML Files Generation.

### ISSUE THREAD

**Issue by hassaanseeker** [abreheret/PixelAnnotationTool#24]
How can we generate XML files for pixel annotated Images.

**Comment by IllidanSR** [comment]
hello! have same question, i use you program, and generate color mask, but for use it with tf, i must convert data to tf records format, and i need xml file. Thx!

**Comment by jiagui1** [comment]
have same question...

**Comment by saurabh241930** [comment]
```
"Traceback (most recent call last):
  File "poly_json.py", line 47, in <module>
    im, contour , hierarchy = cv.findContours(person, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_SIMPLE)
```
"
do you guys how do i fix this ,i am passing every agruments then also I am getting this error

this is my what my command look like
> ` **python poly_json.py --input=/home/saurabh/Pictures/train/cb_32_watershed_mask.png --config=/home/saurabh/Pictures/train/test.json --epsilon=2.5**`

**Comment by abreheret** [comment]
The software is not designed to create a xml file but a segmented image.
