### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by nirajvermafcb** [abreheret/PixelAnnotationTool#25]
I am using Ubuntu 16.04 .

I have performed all the steps mentioned in README and installed all the dependencis. However when I run this step
**cmake -DQT5_DIR=/home/niraj/Qt5.9.1/5.9.1/gcc_64/lib/cmake -G "Unix Makefiles" ..** I encounter this error

_CMake Error: The source directory "/home/niraj" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI._

I don't know where I am going wrong./home/niraj is the path where my Qt5.9.1 resides

**Comment by vijaydwivedi75** [comment]
This is the same error I am getting. Any help?
