### ISSUE TITLE
resizing the color masks somehow messes the color detection

### ISSUE THREAD

**Issue by tanmaypandey7** [abreheret/PixelAnnotationTool#35]
hi, i have labelled around 300 images for my training dataset. unfortunately since i was getting a out of memory error i had to resize all of them including the masks. but when i run a pixel color detection script the resized image detects multiple labels whereas the original ones only show a single color. 
note that all my images have 1 label only, i have no idea why it is doing so.
i'll attach some images for referenece.
original images : 
![2653005010666-1](https://user-images.githubusercontent.com/36691630/55343048-ea70d900-54c7-11e9-89f1-d4a0f93c3864.png)
![3021690011258-10](https://user-images.githubusercontent.com/36691630/55343049-ea70d900-54c7-11e9-81b4-78dc480e06dc.png)
![3021760290057-1](https://user-images.githubusercontent.com/36691630/55343053-ea70d900-54c7-11e9-8b86-810448cf629c.png)
![3021760290422-1](https://user-images.githubusercontent.com/36691630/55343054-eb096f80-54c7-11e9-9553-5c7faa104904.png)
![3021760291047-1](https://user-images.githubusercontent.com/36691630/55343055-eb096f80-54c7-11e9-96f2-2a67bca67698.png)
![2600438012149-1](https://user-images.githubusercontent.com/36691630/55343056-eba20600-54c7-11e9-98dd-ad9ed2be8132.png)
resized ones:
![2653005010666-1](https://user-images.githubusercontent.com/36691630/55343082-fbb9e580-54c7-11e9-8bed-322df410a6d2.png)
![3021690011258-10](https://user-images.githubusercontent.com/36691630/55343083-fbb9e580-54c7-11e9-86be-ec4d52e6e37c.png)
![3021760290057-1](https://user-images.githubusercontent.com/36691630/55343085-fc527c00-54c7-11e9-905b-879a35d58fff.png)
![3021760290422-1](https://user-images.githubusercontent.com/36691630/55343086-fc527c00-54c7-11e9-82a8-94e90ff8c626.png)
![3021760291047-1](https://user-images.githubusercontent.com/36691630/55343087-fc527c00-54c7-11e9-9934-f7a9a4e974b8.png)
![2600438012149-1](https://user-images.githubusercontent.com/36691630/55343081-fb214f00-54c7-11e9-92bd-24e26d20cc92.png)

while pixel_color_detecting the original images:
![Screenshot (42)](https://user-images.githubusercontent.com/36691630/55343815-82bb8d80-54c9-11e9-831e-22b12fbf414b.png)

while for resized:
![Screenshot (43)](https://user-images.githubusercontent.com/36691630/55343821-85b67e00-54c9-11e9-9487-7d29ca5bb3f5.png)

**Comment by abreheret** [comment]
Your issue has nothing to do with Pixel Annotation tools (so I close the issue). 
In addition : 
- you do not provide your resize script
- I dont see the difference between the original image and resize image (the sizes are the same)

But in view of your images, it seems to me that you need (in your script to resize) use a CUBIC or LINEAR interpolation, and therefore the labels border are "averaged". It is necessary to use an interpolation of the NEAREST type.

**Comment by tanmaypandey7** [comment]
since i am a noob at markdown here is the script:
just adding a imgur link to make code a bit understandable
https://imgur.com/K5vc8D1

**Comment by tanmaypandey7** [comment]
thank you, dear sir, simply changing cv2.INTER_AREA TO cv2.INTER_NEAREST did the trick. I cannot thank you enough as you have saved me from labeling 500 images again.
