### ISSUE TITLE
Suggestion: add manual mark to color mask

### ISSUE THREAD

**Issue by captainst** [abreheret/PixelAnnotationTool#39]
Great tool and congrats!

I think that it would be quite useful to add an option to allow the user to add manual mask to the final color mask png. Currently user mark is saved in a seperate png file.

For example, if I want to mark all balloons in the following picture, I would use red color for each balloon, and apply watershed (image taken from matterport mask-rcnn balloon example):
![image](https://user-images.githubusercontent.com/23187023/59488011-ea6e5b80-8eb0-11e9-818a-2784c975a658.png)

It works great. But then I want to "seperate" each balloon from one another. In this case, I might want to draw a thin border using a different color without applying the watershed, and I want this border to be visualizable in the final color png. Currently it is not possible since the color png is a result of the watershed. I think that it could be very useful to mark objects of the same type while overlapping with each other.

Many thanks.

Tom

**Comment by abreheret** [comment]
Sorry, the software was not designed to do this. the quickest solution is to make a balloon id with another color...
