### ISSUE TITLE
1 pixel border around the color_mask

### ISSUE THREAD

**Issue by d4n1elchen** [abreheret/PixelAnnotationTool#40]
Hi, I'm using v1.3.2 to annotate the images for a segmentation problem.

An example of my raw image:
![](https://imgur.com/0XMpLYg.png)

The corresponding labeled image by this tool:
![](https://imgur.com/CCb6Bkn.png)

There're only two labels: foreground (white) and background (red)

Thanks to the watershed algorithm, I can do the manual labeling quickly. However, the saved result contains an unexpected border around the color_mask with 1-pixel width. If you put the color_mask on a dark background, you will notice the border:
![](https://imgur.com/bA3jV8y.png)

The same problem is shown in the watershed_mask file. This somehow affects the performance of my model. I don't want the border.

Is this designed feature or just a bug? I didn't enable "keep border provide by watershed".

**Comment by cusps** [comment]
I am having the same issue, I do not think it should be a feature. The reason your model is likely not performing well with it is it sees the white boundary as an object id (if you don't already have one being white) or sees it as part of another object mask. For example, in your last picture, it is likely combining the object you masked and the boundary, and training on that. This is a very irritating bug.

**Comment by cusps** [comment]
Here is a quick solution in python if you need it:

```
# I am using numpy here FYI, and make sure your mask is converted to greyscale already.

def get_rid_of_white_boundary(mask):
    mask[0] = 0
    mask[-1] = 0
    mask[:, 0] = 0
    mask[:, -1] = 0
```
