### ISSUE TITLE
crashed on image with Chinese file name or folder name

### ISSUE THREAD

**Issue by trigchen** [abreheret/PixelAnnotationTool#41]
PixelAnnotationTool crashed while opening the image which had Chinese character in file name or folder name. 
OS: Windows 7 SP1
PixelAnnotationTool version: v1.3.2

Problem detail:
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	PixelAnnotationTool.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5c669d98
  Fault Module Name:	ucrtbase.DLL
  Fault Module Version:	10.0.14393.2247
  Fault Module Timestamp:	5adc1d0b
  Exception Code:	40000015
  Exception Offset:	000000000006eacf
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	234e
  Additional Information 2:	234e57764cdda6dba0ee3839b79c0dce
  Additional Information 3:	1ebd
  Additional Information 4:	1ebda18eff30a35f06f16bc4164af8f7

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by davinnovation** [comment]
also in Korean, Japanese

**Comment by abreheret** [comment]
Sorry, but the software does not managing Korean, Japanese and Chinese characters. Give me pulls requests if you want to have this feature.
