### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by lucheng07082221** [abreheret/PixelAnnotationTool#42]
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
fatal: 不是一个 git 仓库（或者任何父目录）：.git
fatal: 不是一个 git 仓库（或者任何父目录）：.git
fatal: 不是一个 git 仓库（或者任何父目录）：.git
fatal: 不是一个 git 仓库（或者任何父目录）：.git
-- update git version
CMake Error at CMakeLists.txt:27 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.

CMake Warning at CMakeLists.txt:44 (message):
  Version number of pixel annoation tool is warned

-- Found OpenCV: /usr/local (found version "4.1.1") 
-- Curl is found
-- qmake is found here : /usr/bin/qmake
-- Configuring incomplete, errors occurred!
See also "/home/lc/work/PixelAnnotationTool-1.3.0/x64/CMakeFiles/CMakeOutput.log".

**Comment by bharath5673** [comment]
windows users this is cool..


https://github.com/tenjumh/Pixel-Annotation-Tool

**Comment by abreheret** [comment]
@lucheng07082221 Sorry, I think you have download the code but you must have to clone (with git) the project to be able to compile it because I take (with CMake) the information from the git tag to get the version information.
