### ISSUE TITLE
Background Label

### ISSUE THREAD

**Issue by RailwaysPi** [abreheret/PixelAnnotationTool#46]
I'd like to change an existing mask containing three labels. Two labels are clearly defined, the third is background (id 0) and includes every other undefined object. Now, I have the problem that the watershed algorithm completely removes the background and label its content with another color. Are you concerned about this issue? Is there a way to better specify the background label, e.g. with different configurations in the JSON file?

**Comment by abreheret** [comment]
Hi, 
The best solution is to define an "undefined object" class with a class number other than zero (id! = 0). And keep the zero id for the watershed algorithm filled these pixels. For the moment, there is no possibility to configure class 0 in the JSON file. This id is **reserved** for filling the watershed.
