### ISSUE TITLE
color_mask not created: change color description

### ISSUE THREAD

**Issue by HIN0209** [abreheret/PixelAnnotationTool#5]
Hello, I enjoy this app (v 1.2.0 binary downloaded) with my Ubuntu16.04. I have two issues.

First, I only set 'Manual Mask' option  but no 'Watershed Mask' option, mask with one of the colors manually, and 'Save current image'.  Then, the created xx_color_mask.png is completely dark, while _mask.png shows the mask (based on a jpg RGB image). Please advise how I can get a color mask image. My goal is to mask small areas with 2-3 classes, so watershed mask is not necessarily needed.

The second issue is whether I can change the color labeling description (e.g., red for 'rider', white for 'road marking'), because I am using this for non-driving images, such that custom color description would be more clear for me to label.

Edit: I notice that no area should be unmasked. If so, other areas should be masked as 'neutral'. How do I mask the rest of the area to neutrally mask?

**Comment by abreheret** [comment]
For your first issues, The xx_mask.png is [gray image](https://raw.githubusercontent.com/abreheret/PixelAnnotationTool/master/images_test/Abbey_Road_mask.png). It contains the "R/G/B" with "id/id/id" of labels mask for each pixels. To generate color_mask click on watershed button or press "SPACE BAR" and save. The xx_mask.png image just serves to reproduce the result [image color](https://raw.githubusercontent.com/abreheret/PixelAnnotationTool/master/images_test/Abbey_Road_color_mask.png) and [image watershed](https://raw.githubusercontent.com/abreheret/PixelAnnotationTool/master/images_test/Abbey_Road_watershed_mask.png)

Your second issues, you can change and load (Edit->load) a file.json ([config.json](https://github.com/abreheret/PixelAnnotationTool/blob/master/config.json)) which contain the color/id/name/... of each label. The only constraint is to have a unique id between 0 and 255 for your labels.

**Comment by HIN0209** [comment]
Thank you!! I will try as instructed.

**Comment by HIN0209** [comment]
Hello,

For the issue #1, it works fine.

For the second issue, I tried both binary versions by Ubuntu and Windows. "Edit" only has Undo and Redo, so there is no "load" option. In "Tool", there is "Open config file", but opening the revised config file did not change the color description. Does your advice works only to a build version??

**Comment by abreheret** [comment]
Sorry try with this zip release (in attachement). With this release, I test and its works with my [color_test](https://github.com/abreheret/PixelAnnotationTool/blob/master/color_test.json) 

[PixelAnnotationTool_x64_v1.2.0-7-gfd39e25.zip](https://github.com/abreheret/PixelAnnotationTool/files/1730498/PixelAnnotationTool_x64_v1.2.0-7-gfd39e25.zip)

**Comment by abreheret** [comment]
tell me if ok for you !

**Comment by HIN0209** [comment]
How quick!! I tried this with my Windows 10 and works fine. Appreciate it.
