### ISSUE TITLE
How are the labels saved?

### ISSUE THREAD

**Issue by Gitanjali450** [abreheret/PixelAnnotationTool#50]
Hello,
Thank you very much for the tool. I had a question: how are the labels of a segmented image saved in the tool? Are they saved in a JASON file or some other file format? How can I save the labels from within the tool?
Thank you.

**Comment by abreheret** [comment]
The labels are saved in the same directory as the images. Labeled result are png images and for each pixel you have the label (between 0 at 255), so no JSON or XML file.
