### ISSUE TITLE
unable to build in win10

### ISSUE THREAD

**Issue by elepp** [abreheret/PixelAnnotationTool#66]
this is the error info,what should i do

-- Selecting Windows SDK version 10.0.14393.0 to target Windows 10.0.18363.
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
-- update git version
CMake Error at CMakeLists.txt:27 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.

CMake Warning at CMakeLists.txt:44 (message):
  Version number of pixel annoation tool is warned

-- OpenCV ARCH: x64
-- OpenCV RUNTIME: vc14
-- OpenCV STATIC: OFF
-- Found OpenCV 3.4.9 in D:/opencv/build/x64/vc14/lib
-- You might need to add D:\opencv\build\x64\vc14\bin to your PATH to be able to run your applications.
-- Curl is found
-- Configuring incomplete, errors occurred!
See also "D:/PixelAnnotationTool-master/scripts_to_build/build/x64/CMakeFiles/CMakeOutput.log".

D:\PixelAnnotationTool-master\scripts_to_build\build\x64>cmake --build . --config Release
Microsoft (R) 生成引擎版本 14.0.25420.1
版权所有(C) Microsoft Corporation。保留所有权利。

MSBUILD : error MSB1009: Project file does not exist.
ALL_BUILD.vcxproj

**Comment by abreheret** [comment]
to compile the project it is necessary to have the ".git" directory because meta information is retrieved for compilation (the tags in particular). so clone the project to compile, (no download the zip)
