### ISSUE TITLE
Feature request: Uncap zoom functionality

### ISSUE THREAD

**Issue by Zartris** [abreheret/PixelAnnotationTool#67]
HI this is not so much an issue as a feature request.
I am working on rather large images and it is hard to get an overview of the whole image when there is a zoom (out) cap.
Can we remove this?

**Comment by abreheret** [comment]
Hi, 

I changed the values of the main_window.ui file (7db49e18244917b783a2d75c169800807a5b276b),
You can test this version downloaded (automatic build on a test branch:dev) and test it to see if this configuration suits you.

windows : https://transfer.sh/7ww1T/PixelAnnotationTool_x64_v1.4.0-10-g5dcd7b9.zip
ubuntu Xenial : https://transfer.sh/UktZ6/PixelAnnotationTool_x86_64_v1.4.0-10-g5dcd7b9.AppImage
ubuntu Bionic : https://transfer.sh/129ntO/PixelAnnotationTool_x86_64_v1.4.0-10-g5dcd7b9.AppImage

**Comment by Zartris** [comment]
Absolutely perfect! :D
Thanks a lot

**Comment by Zartris** [comment]
Does this make it to the next release? :) 
I can see you took down the links and I am unable to build It from scratch, so I will be waiting for the next release hoping it is included.

**Comment by abreheret** [comment]
Yes, the links are automatically deleted after 14 days on tranfers.sh, I just restarted the built with [travis](https://travis-ci.org/github/abreheret/PixelAnnotationTool/jobs/761563930#L1348) and [appveyor](https://ci.appveyor.com/project/abreheret/pixelannotationtool#L229) for 14 days : 

- Xenial : https://transfer.sh/Ou8LO/PixelAnnotationTool_x86_64_v1.4.0-10-g5dcd7b9.AppImage
- Bionic : https://transfer.sh/pWQru/PixelAnnotationTool_x86_64_v1.4.0-10-g5dcd7b9.AppImage
- window : https://transfer.sh/12ntQi/PixelAnnotationTool_x64_v1.4.0-10-g5dcd7b9.zip
