### ISSUE TITLE
How to build for Mac

### ISSUE THREAD

**Issue by Nik31** [abreheret/PixelAnnotationTool#69]
I dont see any build instructions for Mac. Is it compatible? If yes can you please add the mac build instructions.

**Comment by abreheret** [comment]
I don't have MacOS, but I imagine that it can work like below: 
> brew install qt
> brew install opencv
> brew install curl
> mkdir build
> cd build
> cmake .. -DCMAKE_BUILD_TYPE=$CONFIG -DDISABLE_MAINTAINER_CFLAGS=off -DCMAKE_PREFIX_PATH=$(brew --prefix qt) -DQMAKE_PATH=$(brew --prefix qt)/bin
