### ISSUE TITLE
random noise pixels around the edge of the color_mask file

### ISSUE THREAD

**Issue by cameron2018** [abreheret/PixelAnnotationTool#7]
im having to crop a few pixels off of each image because there is a random noise of pixels around the edge

**Comment by abreheret** [comment]
I don't understand. Give me some images to explain your issue.

**Comment by kingofprank** [comment]
I have the same problem，it looks like this. 
![98_color_mask](https://user-images.githubusercontent.com/13606974/39955193-66534b72-55fd-11e8-931d-09fd919dc877.png)
![98](https://user-images.githubusercontent.com/13606974/39955199-7c5102b6-55fd-11e8-9324-60861f7d4f01.jpg)
