### ISSUE TITLE
Error while making: ‘Qt::CheckState’ is not a class or namespace

### ISSUE THREAD

**Issue by eyildiz-ugoe** [abreheret/PixelAnnotationTool#8]
Followed the instructions, got the following:

In file included from /home/userName/workspace/PixelAnnotationTool/src/main_window.h:22:0,
                 from /home/userName/workspace/PixelAnnotationTool/src/main_window.cpp:1:
/home/userName/workspace/PixelAnnotationTool/src/image_canvas.h:31:41: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
  void mouseMoveEvent(QMouseEvent * event) override;
                                         ^
/home/userName/workspace/PixelAnnotationTool/src/image_canvas.h:32:42: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
  void mousePressEvent(QMouseEvent * event) override;
                                          ^
/home/userName/workspace/PixelAnnotationTool/src/image_canvas.h:33:38: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
  void keyPressEvent(QKeyEvent * event) override;
                                      ^
/home/userName/workspace/PixelAnnotationTool/src/image_canvas.h:34:37: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
  void wheelEvent(QWheelEvent * event) override;
                                     ^
/home/userName/workspace/PixelAnnotationTool/src/image_canvas.h:35:44: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
  void mouseReleaseEvent(QMouseEvent * event) override;
                                            ^
/home/userName/workspace/PixelAnnotationTool/src/image_canvas.h:36:36: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
  void paintEvent(QPaintEvent *event) override;
                                    ^
```
In file included from /home/userName/workspace/PixelAnnotationTool/src/main_window.h:23:0,
                 from /home/userName/workspace/PixelAnnotationTool/src/main_window.cpp:1:
/home/userName/workspace/PixelAnnotationTool/src/label_widget.h:23:36: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
  void paintEvent(QPaintEvent *event) override;
                                    ^
/home/userName/workspace/PixelAnnotationTool/src/main_window.cpp: In member function ‘void MainWindow::runWatershed()’:
/home/userName/workspace/PixelAnnotationTool/src/main_window.cpp:136:45: error: ‘Qt::CheckState’ is not a class or namespace
  checkbox_watershed_mask->setCheckState(Qt::CheckState::Checked);
                                             ^
/home/userName/workspace/PixelAnnotationTool/src/main_window.cpp: In member function ‘void MainWindow::on_actionOpenDir_triggered()’:
/home/userName/workspace/PixelAnnotationTool/src/main_window.cpp:181:107: error: in C++98 ‘ext_img’ must be initialized by constructor, not by ‘{...}’
  static QStringList ext_img = { "png","jpg","bmp","pgm","jpeg" ,"jpe" ,"jp2" ,"pbm" ,"ppm" ,"tiff" ,"tif" };
                                                                                                           ^
/home/userName/workspace/PixelAnnotationTool/src/main_window.cpp:181:107: error: could not convert ‘{"png", "jpg", "bmp", "pgm", "jpeg", "jpe", "jp2", "pbm", "ppm", "tiff", "tif"}’ from ‘<brace-enclosed initializer list>’ to ‘QStringList’
CMakeFiles/PixelAnnotationTool.dir/build.make:66: recipe for target 'CMakeFiles/PixelAnnotationTool.dir/src/main_window.cpp.o' failed
make[2]: *** [CMakeFiles/PixelAnnotationTool.dir/src/main_window.cpp.o] Error 1
CMakeFiles/Makefile2:131: recipe for target 'CMakeFiles/PixelAnnotationTool.dir/all' failed
make[1]: *** [CMakeFiles/PixelAnnotationTool.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

Running on Ubuntu 16.04.

**Comment by abreheret** [comment]
The project build on Ubuntu show [travis log](https://travis-ci.org/abreheret/PixelAnnotationTool)
If you can not build it,  at the end of "travis log" you can download the result binary : 
![image](https://user-images.githubusercontent.com/7152894/37968429-5f53aa54-31ce-11e8-80fd-b23d567b338c.png)
https://transfer.sh/8WFGj/PixelAnnotationTool_x86_64_v1.2.1-6-g8c78e1c.AppImage ( this download is available during 14 days after the last push).
To use this binary, chmod +x on this file , and run it.
