### ISSUE TITLE
How to set the right labels in mask

### ISSUE THREAD

**Issue by mldm4** [abreheret/PixelAnnotationTool#9]
Great work and thanks for your tool.

I wonder how the provided labels can be modified to use the masks IDs I desire.

For example, I have a "pencil" instance and a "background" instance in the image I want to get masked. If I color the pencil in the image with a "traffic sign" predefined label and leave the rest without coloring I will have in my output manual the uncolored background with pixel value 0 and the pencil instance with pixel value 19 (which is the traffic sign ID). As I only have one label ("pencil" label), I would like to use the ID number 1 to color the pencil instance. The problem is that if I select the label with ID=1, which belongs to "ego-vehicle", I cannot color anything. I guess this is due to the fact that the "ego-vehicle" is supposed to be discarded and assumed as background. Therefore, how can I get to use the ID I want to mask an image that is not supposed to stick to the predefined labels you provide?

I hope I explained myself accurately.
Thanks again.

**Comment by abreheret** [comment]
If that can help you, for customize the label : you can change and load (Tools->Open Config File) a file.json ([config.json](https://github.com/abreheret/PixelAnnotationTool/blob/master/config.json)) which contain the color/id/name/... of each label. The only constraint is to have a unique id between 0 and 255 for your labels. a simple example is [here](https://github.com/abreheret/PixelAnnotationTool/blob/master/color_test.json)

**Comment by mldm4** [comment]
Great, thank you, but whenever I have tried to click on Open Config it hangs and I have to force quit.

**Comment by abreheret** [comment]
Ok, its works on my windows OS, 
Are you on linux or windows, and if you are under linux you use what distribution ?

**Comment by mldm4** [comment]
I am using Ubuntu 16.04

**Comment by ETucks** [comment]
I have the same issue that the program freezes after clicking tools -> open config. I'm also using linux 16.04

**Comment by abreheret** [comment]
Is this problem still present in [v1.3.1](https://github.com/abreheret/PixelAnnotationTool/releases/tag/v1.3.1)
